
import type { FoodItem } from './types';

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: 1,
    name: 'Jollof Rice',
    price: 1200,
    image: 'https://images.pexels.com/photos/10759247/pexels-photo-10759247.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Rich and incredibly tasty rice dish, made with reduced tomatoes, bell peppers, chili peppers, onions, herbs and seasoning.',
    rating: 4.5,
    reviews: 59,
    category: 'Meals',
    calories: 248,
  },
  {
    id: 2,
    name: 'Spicy Noodles',
    price: 1500,
    image: 'https://images.pexels.com/photos/2456435/pexels-photo-2456435.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'A delicious and spicy noodle dish with fresh vegetables and a perfectly boiled egg.',
    rating: 4.8,
    reviews: 82,
    category: 'Meals',
    calories: 310,
  },
  {
    id: 3,
    name: 'Shrimp Pasta',
    price: 1800,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Creamy pasta with succulent shrimp, garlic, and a hint of lemon.',
    rating: 4.7,
    reviews: 65,
    category: 'Meals',
    calories: 420,
  },
  {
    id: 4,
    name: 'Vegetable Curry',
    price: 1200,
    image: 'https://images.pexels.com/photos/674574/pexels-photo-674574.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'A flavorful mix of seasonal vegetables in a rich and aromatic curry sauce, served with white rice.',
    rating: 4.4,
    reviews: 45,
    category: 'Meals',
    calories: 280,
  },
  {
    id: 5,
    name: 'Mixed Salad',
    price: 1500,
    image: 'https://images.pexels.com/photos/1211887/pexels-photo-1211887.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'A healthy and refreshing salad with mixed greens, tomatoes, cucumbers, and a light vinaigrette.',
    rating: 4.6,
    reviews: 71,
    category: 'Sides',
    calories: 150,
  },
  {
    id: 6,
    name: 'Chicken Pasta Salad',
    price: 1500,
    image: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Grilled chicken and pasta tossed with fresh vegetables and a creamy dressing.',
    rating: 4.7,
    reviews: 93,
    category: 'Meals',
    calories: 350,
  },
  {
    id: 7,
    name: 'Beef Salad',
    price: 1200,
    image: 'https://images.pexels.com/photos/3662132/pexels-photo-3662132.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Tender strips of beef on a bed of fresh greens, with a tangy dressing.',
    rating: 4.5,
    reviews: 55,
    category: 'Meals',
    calories: 320,
  },
  {
    id: 8,
    name: 'Fried Plantain',
    price: 300,
    image: 'https://images.pexels.com/photos/4055243/pexels-photo-4055243.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Sweet, ripe plantains fried to golden perfection. A perfect side for any meal.',
    rating: 4.9,
    reviews: 120,
    category: 'Sides',
    calories: 200,
  },
  {
    id: 9,
    name: 'Coleslaw',
    price: 800,
    image: 'https://images.pexels.com/photos/8963453/pexels-photo-8963453.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crisp and creamy coleslaw made with fresh cabbage and carrots.',
    rating: 4.3,
    reviews: 30,
    category: 'Sides',
    calories: 180,
  },
  {
    id: 10,
    name: 'Fried Chicken',
    price: 900,
    image: 'https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crispy and juicy fried chicken, seasoned with a special blend of herbs and spices.',
    rating: 4.8,
    reviews: 150,
    category: 'Sides',
    calories: 380,
  },
];
